sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-titles-from-headings
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
url: https://docs.mbaasy.com
title: Mbaasy docs
permalink: pretty
twitter:
  username: mbaasy
